modLoader="javafml" #mandatory
loaderVersion="[26,)" #mandatory (26 is current forge version)
[[mods]] #mandatory
modId="yastm" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Yet Another Simple Telporter Mod" #mandatory
# The description text for the mod (multi line!) (#mandatory)
description='''
Telporters !
'''